server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/Work/native-file-repo
        git:
#          uri: file:///Users/kimkiyun/Desktop/Work/git-local-repo
          uri: https://github.com/keeeeeey/spring-cloud-config.git
#          username: [your username]
#          password: [your password]